followup_question_task:
  name: followup_question_task
  description: >
    User has requested: {prompt}.
    User Requested Style in the prompt: {style}.
    User Conversation History: {history}
    User ActorId: {actorId}
    Analyse the user prompt - {prompt}. After that answer the question based on the already conducted research
    aligning with the user prompt.
  expected_output: >
    Output is supposed to be a string
  agent: followup_question_agent

